### ISSUE TITLE
When the paper will be released? Thx

### ISSUE THREAD

**Issue by StriveZs** [CLAY-3D/OpenCLAY#2]
Hi, Thx for the awesome work, I kindly want to know when the paper will be released >_<

Paper will be released in this week and the code will be released during SIGGRAPH

_Originally posted by @eEhyQx in https://github.com/CLAY-3D/OpenCLAY/issues/1#issuecomment-2134814250_

**Comment by eEhyQx** [comment]
It's strange but Arxiv already "hold on" the paper for about 1 week...We don't know what's happening...usually it only takes 2-3 days

**Comment by StriveZs** [comment]
<img width="767" alt="image" src="https://github.com/CLAY-3D/OpenCLAY/assets/28866063/30b12e9e-fc8e-45d4-b05f-8206e476f4f4">

Yep, looks like we need more patience to await good news~

**Comment by doublexxking** [comment]
Any good news?

**Comment by eEhyQx** [comment]
It's so confused, we don't know what's going on, we just send an new e-mail to argue.
